# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://luiyo.net"
DefaultContentLanguage  = "en"
title                   = "Luiyología"
theme                   = "hugo-future-imperfect-slim"
paginate                = 10
disqusShortname         = "luiyologia"
googleAnalytics         = "UA-555064-1"
pluralizeListTitles     = false
disableLanguages        = [""]
ignoreErrors = ["error-remote-getjson"]

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  mainSections          = ["blog", "post"]
  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default", "/css/luiyologia.css"]
  enableCDN             = false
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/blog/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = true
  imageStretch          = ""
  removeBlur            = true
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "email"]
  hideEmptyStats        = false

  [params.meta]
    # Sets the meta tag description
    description         = "The Science that studies my interests and concerns"
    # Sets the meta tag author
    author              = "Luis García Castro"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "Luiyología"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = ""
    paragraph             = "The Science that studies my interests and concerns"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = ""
      width               = "300"
      alt                 = "Luiyología"
      src                 = "/img/main/Luiyologia-twitterlogo.png"

  [params.sidebar]
    about               = "Ludopath, technopath, cinephile, skeptic and, by every definition, early adopter"
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 5
    # set to show or to hide categories in the sidebar
    categories          = false
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = false
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = false

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "https://luiyo.net/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Travel CV"
    identifier        = "travelCV"
    url               = "/travel-cv/"
    pre               = "<i class='fas fa-globe-europe'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Talks"
    identifier        = "talks"
    url               = "/talks/"
    pre               = "<i class='fas fa-microphone'></i>"
    weight            = 6

  [[menu.main]]
    name              = "RSS"
    identifier        = "rss"
    url               = "/feed.xml"
    pre               = "<i class='fas fa-rss'></i>"
    weight            = 7

[Languages]
  # Each language has its own menu.

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Español"
    title               = "Luiyología en Español"
    description         = "La Ciencia que estudia mis intereses y preocupaciones"
    weight              = 2

    [[Languages.es.menu.main]]
      name              = "Inicio"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.es.menu.main]]
      name              = "Acerca de"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.es.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.es.menu.main]]
      name              = "Etiquetas"
      identifier        = "tags"
      url               = "/tags/"
      pre               = "<i class='fas fa-tags'></i>"
      weight            = 4

    [[Languages.es.menu.main]]
      name              = "Travel CV"
      identifier        = "travelCV"
      url               = "/travel-cv/"
      pre               = "<i class='fas fa-globe-europe'></i>"
      weight            = 5

    [[Languages.es.menu.main]]
      name              = "Charlas"
      identifier        = "talks"
      url               = "/talks/"
      pre               = "<i class='fas fa-microphone'></i>"
      weight            = 6

    [[Languages.es.menu.main]]
      name              = "RSS"
      identifier        = "rss"
      url               = "/blog/feed.xml"
      pre               = "<i class='fas fa-rss'></i>"
      weight            = 7

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github                = "luisgc"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = "luiyo"
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "luisgc"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = "LuisGarcaCastro"
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = "Luiyo"
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "luiyo"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = "luiyologia@gmail.com"
