name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.159.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Importante si tu tema es un submódulo
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify --baseURL "https://luiyo.net/" --cleanDestinationDir

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Aquí está el truco: subimos el contenido de public, no la carpeta entera
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4